name: Arduino Library CI

on: [pull_request, push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: jepler/actions-arduino-ci@main
      with:
        pretty-name: 'Adafruit SI1145 Arduino Library'
        repo-token: ${{ secrets.GH_REPO_TOKEN }}
